  [build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://reportifybackend.vercel.app/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200