[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  base = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://reportify-backend.vercel.app/api/:splat"
  status = 200
  force = true