[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://reportifybackendhere.vercel.app/api/:splat"
  status = 200
  force = true